import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
import java.util.Random;

public class Ahorcado extends javax.swing.JFrame {
    
    private String palabraActual;
    private String pistaActual;
    private int nivelSeleccionado = 1;
       
    public static final String[] palabras1 = {"PARADIGMAS", "CLASE", "OBJETO"};
    public static final String[] pistas1 = {"Tipos de programación", "Estructura en POO", "Instancia de una clase"};

    public static final String[] palabras2 = {"HERENCIA", "POLIMORFISMO", "ENCAPSULAMIENTO"};
    public static final String[] pistas2 = {
        "Permite que una clase herede atributos y métodos de otra",
        "Permite que objetos se comporten de manera similar a través de una interfaz común",
        "Oculta los detalles internos de una clase y expone solo lo necesario"
    };

    public static final String[] palabras3 = {"ABSTRACTA", "ABSTRACTO", "SOBRECARGA"};
    public static final String[] pistas3 = {
        "Clase que no se puede instanciar directamente y se utiliza como base",
        "Método declarado en una clase abstracta sin implementación concreta",
        "Permite definir varios métodos con el mismo nombre pero con diferentes parámetros"
    };
    
    public int vidas = 3;
    /**
     * Creates new form Menu
     */
    public Ahorcado() {
        initComponents();
        iniciarParpadeo();
        iniciarJuego();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ahorcado = new javax.swing.JDialog();
        panelContenedorPistas = new javax.swing.JPanel();
        panelPistas = new javax.swing.JPanel();
        txtPalabra = new javax.swing.JLabel();
        txtPista = new javax.swing.JLabel();
        vida1 = new javax.swing.JLabel();
        vida3 = new javax.swing.JLabel();
        vida2 = new javax.swing.JLabel();
        panelAhorcado = new javax.swing.JPanel();
        poste = new javax.swing.JLabel();
        cabeza = new javax.swing.JLabel();
        cuerpo = new javax.swing.JLabel();
        panelTeclado = new javax.swing.JPanel();
        A = new javax.swing.JButton();
        B = new javax.swing.JButton();
        C = new javax.swing.JButton();
        D = new javax.swing.JButton();
        E = new javax.swing.JButton();
        F = new javax.swing.JButton();
        G = new javax.swing.JButton();
        H = new javax.swing.JButton();
        I = new javax.swing.JButton();
        J = new javax.swing.JButton();
        K = new javax.swing.JButton();
        L = new javax.swing.JButton();
        M = new javax.swing.JButton();
        N = new javax.swing.JButton();
        Ñ = new javax.swing.JButton();
        O = new javax.swing.JButton();
        P = new javax.swing.JButton();
        Q = new javax.swing.JButton();
        R = new javax.swing.JButton();
        S = new javax.swing.JButton();
        T = new javax.swing.JButton();
        U = new javax.swing.JButton();
        V = new javax.swing.JButton();
        W = new javax.swing.JButton();
        X = new javax.swing.JButton();
        Y = new javax.swing.JButton();
        Z = new javax.swing.JButton();
        Reset = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        txtPalabraCorrecta = new javax.swing.JLabel();
        txtPerdiste = new javax.swing.JLabel();
        txtLapalabraes = new javax.swing.JLabel();
        btnContinuar = new javax.swing.JButton();
        btnReintentar = new javax.swing.JButton();
        Inicio = new javax.swing.JPanel();
        btnPlay = new javax.swing.JButton();
        jcbNiveles = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        txtDificultad = new javax.swing.JLabel();
        btnTutorial = new javax.swing.JButton();
        txtBienvenido = new javax.swing.JLabel();

        Ahorcado.setTitle("AHORCADO");
        Ahorcado.setPreferredSize(new java.awt.Dimension(1800, 900));
        Ahorcado.setResizable(false);
        Ahorcado.setSize(new java.awt.Dimension(1800, 900));
        Ahorcado.getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        panelContenedorPistas.setBackground(new java.awt.Color(153, 204, 255));
        panelContenedorPistas.setLayout(new java.awt.GridLayout(1, 0));

        panelPistas.setBackground(new java.awt.Color(153, 204, 255));

        txtPalabra.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtPalabra.setForeground(new java.awt.Color(0, 0, 0));

        txtPista.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtPista.setForeground(new java.awt.Color(0, 0, 0));

        vida1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        vida1.setForeground(new java.awt.Color(0, 0, 0));
        vida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/corazon90.png"))); // NOI18N
        vida1.setText("a");

        vida3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        vida3.setForeground(new java.awt.Color(0, 0, 0));
        vida3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/corazon90.png"))); // NOI18N
        vida3.setText("a");

        vida2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        vida2.setForeground(new java.awt.Color(0, 0, 0));
        vida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/corazon90.png"))); // NOI18N
        vida2.setText("a");

        javax.swing.GroupLayout panelPistasLayout = new javax.swing.GroupLayout(panelPistas);
        panelPistas.setLayout(panelPistasLayout);
        panelPistasLayout.setHorizontalGroup(
            panelPistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPistasLayout.createSequentialGroup()
                .addGroup(panelPistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPistasLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtPista, javax.swing.GroupLayout.PREFERRED_SIZE, 855, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPistasLayout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(vida1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vida2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vida3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPistasLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(txtPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPistasLayout.setVerticalGroup(
            panelPistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPistasLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(txtPista, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(txtPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(panelPistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vida1)
                    .addComponent(vida3)
                    .addComponent(vida2))
                .addContainerGap())
        );

        panelContenedorPistas.add(panelPistas);

        panelAhorcado.setBackground(new java.awt.Color(153, 255, 204));

        poste.setText("POSTE");

        cabeza.setText("CABEZA");

        cuerpo.setText("CUERPO");

        javax.swing.GroupLayout panelAhorcadoLayout = new javax.swing.GroupLayout(panelAhorcado);
        panelAhorcado.setLayout(panelAhorcadoLayout);
        panelAhorcadoLayout.setHorizontalGroup(
            panelAhorcadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAhorcadoLayout.createSequentialGroup()
                .addContainerGap(462, Short.MAX_VALUE)
                .addGroup(panelAhorcadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cuerpo)
                    .addGroup(panelAhorcadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cabeza)
                        .addComponent(poste)))
                .addGap(372, 372, 372))
        );
        panelAhorcadoLayout.setVerticalGroup(
            panelAhorcadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAhorcadoLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(poste)
                .addGap(69, 69, 69)
                .addComponent(cabeza)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(cuerpo)
                .addGap(126, 126, 126))
        );

        poste.setVisible(false);
        cabeza.setVisible(false);
        cuerpo.setVisible(false);

        panelContenedorPistas.add(panelAhorcado);

        Ahorcado.getContentPane().add(panelContenedorPistas);

        panelTeclado.setBackground(new java.awt.Color(204, 204, 255));
        panelTeclado.setLayout(new java.awt.GridLayout(3, 9));

        A.setText("A");
        A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AActionPerformed(evt);
            }
        });
        panelTeclado.add(A);

        B.setText("B");
        B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActionPerformed(evt);
            }
        });
        panelTeclado.add(B);

        C.setText("C");
        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });
        panelTeclado.add(C);

        D.setText("D");
        D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DActionPerformed(evt);
            }
        });
        panelTeclado.add(D);

        E.setText("E");
        E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EActionPerformed(evt);
            }
        });
        panelTeclado.add(E);

        F.setText("F");
        F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FActionPerformed(evt);
            }
        });
        panelTeclado.add(F);

        G.setText("G");
        G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GActionPerformed(evt);
            }
        });
        panelTeclado.add(G);

        H.setText("H");
        H.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HActionPerformed(evt);
            }
        });
        panelTeclado.add(H);

        I.setText("I");
        I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IActionPerformed(evt);
            }
        });
        panelTeclado.add(I);

        J.setText("J");
        J.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JActionPerformed(evt);
            }
        });
        panelTeclado.add(J);

        K.setText("K");
        K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KActionPerformed(evt);
            }
        });
        panelTeclado.add(K);

        L.setText("L");
        L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LActionPerformed(evt);
            }
        });
        panelTeclado.add(L);

        M.setText("M");
        M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MActionPerformed(evt);
            }
        });
        panelTeclado.add(M);

        N.setText("N");
        N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NActionPerformed(evt);
            }
        });
        panelTeclado.add(N);

        Ñ.setText("Ñ");
        Ñ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ÑActionPerformed(evt);
            }
        });
        panelTeclado.add(Ñ);

        O.setText("O");
        O.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OActionPerformed(evt);
            }
        });
        panelTeclado.add(O);

        P.setText("P");
        P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PActionPerformed(evt);
            }
        });
        panelTeclado.add(P);

        Q.setText("Q");
        Q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QActionPerformed(evt);
            }
        });
        panelTeclado.add(Q);

        R.setText("R");
        R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RActionPerformed(evt);
            }
        });
        panelTeclado.add(R);

        S.setText("S");
        S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SActionPerformed(evt);
            }
        });
        panelTeclado.add(S);

        T.setText("T");
        T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TActionPerformed(evt);
            }
        });
        panelTeclado.add(T);

        U.setText("U");
        U.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UActionPerformed(evt);
            }
        });
        panelTeclado.add(U);

        V.setText("V");
        V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VActionPerformed(evt);
            }
        });
        panelTeclado.add(V);

        W.setText("W");
        W.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WActionPerformed(evt);
            }
        });
        panelTeclado.add(W);

        X.setText("X");
        X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XActionPerformed(evt);
            }
        });
        panelTeclado.add(X);

        Y.setText("Y");
        Y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YActionPerformed(evt);
            }
        });
        panelTeclado.add(Y);

        Z.setText("Z");
        Z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZActionPerformed(evt);
            }
        });
        panelTeclado.add(Z);

        Ahorcado.getContentPane().add(panelTeclado);

        Reset.setTitle("PERDISTE");
        Reset.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Reset.setModal(true);
        Reset.setResizable(false);
        Reset.setSize(new java.awt.Dimension(800, 800));
        Reset.getContentPane().setLayout(new java.awt.GridLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 800));
        jPanel1.setLayout(null);

        txtPalabraCorrecta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtPalabraCorrecta.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtPalabraCorrecta);
        txtPalabraCorrecta.setBounds(200, 260, 390, 80);

        txtPerdiste.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtPerdiste.setForeground(new java.awt.Color(0, 204, 204));
        txtPerdiste.setText("Has perdido!!!");
        jPanel1.add(txtPerdiste);
        txtPerdiste.setBounds(310, 80, 170, 80);

        txtLapalabraes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtLapalabraes.setForeground(new java.awt.Color(0, 0, 0));
        txtLapalabraes.setText("La palabra correcta es:");
        jPanel1.add(txtLapalabraes);
        txtLapalabraes.setBounds(270, 200, 300, 50);

        btnContinuar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(255, 255, 255));
        btnContinuar.setText("Continuar");
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        jPanel1.add(btnContinuar);
        btnContinuar.setBounds(210, 400, 160, 70);

        btnReintentar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnReintentar.setForeground(new java.awt.Color(255, 255, 255));
        btnReintentar.setText("Reintentar");
        btnReintentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReintentarActionPerformed(evt);
            }
        });
        jPanel1.add(btnReintentar);
        btnReintentar.setBounds(440, 400, 160, 70);

        Reset.getContentPane().add(jPanel1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INICIO");
        setSize(new java.awt.Dimension(800, 800));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        Inicio.setBackground(new java.awt.Color(102, 102, 255));
        Inicio.setLayout(null);

        btnPlay.setBackground(new java.awt.Color(153, 204, 255));
        btnPlay.setForeground(new java.awt.Color(255, 255, 255));
        btnPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jugar 90x90.png"))); // NOI18N
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });
        Inicio.add(btnPlay);
        btnPlay.setBounds(390, 380, 140, 100);

        jcbNiveles.setBackground(new java.awt.Color(102, 102, 102));
        jcbNiveles.setForeground(new java.awt.Color(255, 255, 255));
        jcbNiveles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIVEL 1", "NIVEL 2", "NIVEL 3" }));
        jcbNiveles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbNivelesActionPerformed(evt);
            }
        });
        Inicio.add(jcbNiveles);
        jcbNiveles.setBounds(400, 300, 120, 50);

        txtNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setText("INGRESE SU NOMBRE");
        Inicio.add(txtNombre);
        txtNombre.setBounds(350, 120, 240, 50);

        tfNombre.setBackground(new java.awt.Color(102, 102, 102));
        tfNombre.setForeground(new java.awt.Color(255, 255, 255));
        Inicio.add(tfNombre);
        tfNombre.setBounds(360, 180, 190, 30);

        txtDificultad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDificultad.setForeground(new java.awt.Color(255, 255, 255));
        txtDificultad.setText("SELECCIONE LA DIFICULTAD");
        Inicio.add(txtDificultad);
        txtDificultad.setBounds(330, 230, 250, 50);

        btnTutorial.setBackground(new java.awt.Color(51, 51, 51));
        btnTutorial.setForeground(new java.awt.Color(255, 255, 255));
        btnTutorial.setText("TUTORIAL");
        Inicio.add(btnTutorial);
        btnTutorial.setBounds(390, 490, 140, 50);

        txtBienvenido.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        txtBienvenido.setForeground(new java.awt.Color(0, 204, 204));
        txtBienvenido.setText("BIENVENIDO");
        Inicio.add(txtBienvenido);
        txtBienvenido.setBounds(350, 50, 220, 60);

        getContentPane().add(Inicio);

        setBounds(0, 0, 943, 665);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        Ahorcado.setModal(true);
        Ahorcado.setBounds(10,10,1800,900);
        Ahorcado.setVisible(true);
        iniciarJuego();
    }//GEN-LAST:event_btnPlayActionPerformed

    private void BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActionPerformed
        botonLetraPresionado('B');
    }//GEN-LAST:event_BActionPerformed

    private void AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AActionPerformed
        botonLetraPresionado('A');
    }//GEN-LAST:event_AActionPerformed

    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed
        botonLetraPresionado('C');
    }//GEN-LAST:event_CActionPerformed

    private void DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DActionPerformed
        botonLetraPresionado('D');
    }//GEN-LAST:event_DActionPerformed

    private void EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EActionPerformed
        botonLetraPresionado('E');
    }//GEN-LAST:event_EActionPerformed

    private void FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FActionPerformed
        botonLetraPresionado('F');
    }//GEN-LAST:event_FActionPerformed

    private void GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GActionPerformed
        botonLetraPresionado('G');
    }//GEN-LAST:event_GActionPerformed

    private void HActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HActionPerformed
        botonLetraPresionado('H');
    }//GEN-LAST:event_HActionPerformed

    private void IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IActionPerformed
        botonLetraPresionado('I');
    }//GEN-LAST:event_IActionPerformed

    private void JActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JActionPerformed
        botonLetraPresionado('J');
    }//GEN-LAST:event_JActionPerformed

    private void KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KActionPerformed
        botonLetraPresionado('K');                
    }//GEN-LAST:event_KActionPerformed

    private void LActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LActionPerformed
        botonLetraPresionado('L');
    }//GEN-LAST:event_LActionPerformed

    private void MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MActionPerformed
        botonLetraPresionado('M');
    }//GEN-LAST:event_MActionPerformed

    private void NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NActionPerformed
        botonLetraPresionado('N');
    }//GEN-LAST:event_NActionPerformed

    private void ÑActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ÑActionPerformed
        botonLetraPresionado('Ñ');
    }//GEN-LAST:event_ÑActionPerformed

    private void OActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OActionPerformed
        botonLetraPresionado('O');
    }//GEN-LAST:event_OActionPerformed

    private void PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PActionPerformed
        botonLetraPresionado('P');
    }//GEN-LAST:event_PActionPerformed

    private void QActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QActionPerformed
        botonLetraPresionado('Q');
    }//GEN-LAST:event_QActionPerformed

    private void RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RActionPerformed
        botonLetraPresionado('R');
    }//GEN-LAST:event_RActionPerformed

    private void SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SActionPerformed
        botonLetraPresionado('S');
    }//GEN-LAST:event_SActionPerformed

    private void TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TActionPerformed
        botonLetraPresionado('T');
    }//GEN-LAST:event_TActionPerformed

    private void UActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UActionPerformed
        botonLetraPresionado('U');
    }//GEN-LAST:event_UActionPerformed

    private void VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VActionPerformed
        botonLetraPresionado('V');
    }//GEN-LAST:event_VActionPerformed

    private void WActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WActionPerformed
        botonLetraPresionado('W');
    }//GEN-LAST:event_WActionPerformed

    private void XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XActionPerformed
        botonLetraPresionado('X');
    }//GEN-LAST:event_XActionPerformed

    private void YActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YActionPerformed
        botonLetraPresionado('Y');
    }//GEN-LAST:event_YActionPerformed

    private void ZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZActionPerformed
        botonLetraPresionado('Z');
    }//GEN-LAST:event_ZActionPerformed

    private void jcbNivelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbNivelesActionPerformed
        String nivel = (String) ((javax.swing.JComboBox) evt.getSource()).getSelectedItem();
        switch (nivel) {
            case "NIVEL 1":
                nivelSeleccionado = 1;
                break;
            case "NIVEL 2":
                nivelSeleccionado = 2;
                break;
            case "NIVEL 3":
                nivelSeleccionado = 3;
                break;
            default:
                nivelSeleccionado = 1;
                break;
        }
        iniciarJuego(); // Agregamos esta línea para iniciar el juego cuando se cambie el nivel
    }//GEN-LAST:event_jcbNivelesActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
         Reset.dispose();
         Ahorcado.dispose();
         reset();
         
    }//GEN-LAST:event_btnContinuarActionPerformed

    private void btnReintentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReintentarActionPerformed
         reiniciarJuego(); // Llamar a la función para reiniciar el juego
         Reset.dispose(); // Cerrar el diálogo
    }//GEN-LAST:event_btnReintentarActionPerformed


    public void iniciarParpadeo() {   
        Timer timer = new Timer(500, new ActionListener() {
            boolean visible = true;

            @Override
            public void actionPerformed(ActionEvent evt) {
                txtBienvenido.setVisible(visible);
                visible = !visible;
            }
        });
        timer.start(); 
    }   
    
    public void iniciarJuego() {
        seleccionarPalabraYPista();
        mostrarPista();
    }

    private void seleccionarPalabraYPista() {
        Random random = new Random();
        String[] palabras;
        String[] pistas;

        switch (nivelSeleccionado) {
            case 2:
                palabras = palabras2;
                pistas = pistas2;
                break;
            case 3:
                palabras = palabras3;
                pistas = pistas3;
                break;
            case 1:
            default:
                palabras = palabras1;
                pistas = pistas1;
                break;
        }

        int indice = random.nextInt(palabras.length);
        palabraActual = palabras[indice];
        pistaActual = pistas[indice];
    }

    private String generarPalabraOculta(String palabra) {
        StringBuilder palabraOculta = new StringBuilder();
        for (int i = 0; i < palabra.length(); i++) {
            palabraOculta.append("_ ");
        }
        return palabraOculta.toString();
    }

    private void mostrarPista() {
        txtPista.setText("Pista: " + pistaActual);
        txtPalabra.setText(generarPalabraOculta(palabraActual));
    }

    
    private void botonLetraPresionado(char letra) {
    // Verificar si la letra está en la palabra objetivo
    if (palabraActual.contains(String.valueOf(letra))) {
        // La letra está en la palabra, actualizar la palabraLabel con la letra en las posiciones correspondientes
            actualizarPalabraLabel(letra);
        } else {
        // La letra no está en la palabra, perder una vida y mostrar una parte del ahorcado
            mostrarAhorcado();
        }
    }

    private void actualizarPalabraLabel(char letra) {
    // Convierte la palabra actual a un arreglo de caracteres para poder modificarla
    char[] palabraOcultaArray = txtPalabra.getText().toCharArray();

    // Itera sobre la palabra actual y actualiza las posiciones correspondientes con la letra adivinada
    for (int i = 0; i < palabraActual.length(); i++) {
        if (palabraActual.charAt(i) == letra) {
            // Si la letra adivinada coincide con la letra en la posición i de la palabra actual,
            // actualiza la posición correspondiente en el arreglo de caracteres
            palabraOcultaArray[i * 2] = letra; // Se multiplica por 2 porque hay un espacio entre cada letra en la representación de la palabra oculta
        }
    }

    // Convierte el arreglo de caracteres actualizado de nuevo a una cadena y actualiza el texto en txtPalabra
    txtPalabra.setText(new String(palabraOcultaArray));
}

  
     // Método para mostrar una parte del ahorcado cuando el jugador pierde una vida
    private void mostrarAhorcado() {
        if (vidas > 0) {
            vidas--;
            switch (vidas) {
                case 2:
                    vida3.setVisible(false); // Oculta el tercer corazón
                    break;
                case 1:
                    vida2.setVisible(false); // Oculta el segundo corazón
                    break;
                case 0:
                    vida1.setVisible(false); // Oculta el primer corazón
                    mostrarDialogoPerder();
                    break;
            }
            // Muestra el poste, cabeza y cuerpo
            switch (vidas) {
                case 2:
                    poste.setVisible(true);
                    break;
                case 1:
                    cabeza.setVisible(true);
                    break;
                case 0:
                    cuerpo.setVisible(true);
                    break;
            }
        }
    }
    
    
    public void mostrarDialogoPerder() {
        Reset.setModal(true);
        Reset.setBounds(10,10,800,800);
        Reset.setVisible(true);

        // Crear el campo de texto para mostrar la palabra correcta
        txtPalabraCorrecta.setText(palabraActual);      
    }
    
    public void reiniciarJuego() {
        // Restablecer las vidas
        vidas = 3;
        // Mostrar nuevamente los corazones y ocultar el ahorcado
        vida1.setVisible(true);
        vida2.setVisible(true);
        vida3.setVisible(true);
        poste.setVisible(false);
        cabeza.setVisible(false);
        cuerpo.setVisible(false); 
        // Seleccionar una nueva palabra y pista
        seleccionarPalabraYPista();
        // Mostrar la nueva pista y la palabra oculta
        mostrarPista();
    }
    
    public void reset(){
        // Restablecer las vidas
        vidas = 3;
        // Mostrar nuevamente los corazones y ocultar el ahorcado
        vida1.setVisible(true);
        vida2.setVisible(true);
        vida3.setVisible(true);
        poste.setVisible(false);
        cabeza.setVisible(false);
        cuerpo.setVisible(false);
    }
       
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ahorcado().setVisible(true);
            }
        });
    }  
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A;
    private javax.swing.JDialog Ahorcado;
    private javax.swing.JButton B;
    private javax.swing.JButton C;
    private javax.swing.JButton D;
    private javax.swing.JButton E;
    private javax.swing.JButton F;
    private javax.swing.JButton G;
    private javax.swing.JButton H;
    private javax.swing.JButton I;
    private javax.swing.JPanel Inicio;
    private javax.swing.JButton J;
    private javax.swing.JButton K;
    private javax.swing.JButton L;
    private javax.swing.JButton M;
    private javax.swing.JButton N;
    private javax.swing.JButton O;
    private javax.swing.JButton P;
    private javax.swing.JButton Q;
    private javax.swing.JButton R;
    private javax.swing.JDialog Reset;
    private javax.swing.JButton S;
    private javax.swing.JButton T;
    private javax.swing.JButton U;
    private javax.swing.JButton V;
    private javax.swing.JButton W;
    private javax.swing.JButton X;
    private javax.swing.JButton Y;
    private javax.swing.JButton Z;
    private javax.swing.JButton btnContinuar;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnReintentar;
    private javax.swing.JButton btnTutorial;
    private javax.swing.JLabel cabeza;
    private javax.swing.JLabel cuerpo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jcbNiveles;
    private javax.swing.JPanel panelAhorcado;
    private javax.swing.JPanel panelContenedorPistas;
    private javax.swing.JPanel panelPistas;
    private javax.swing.JPanel panelTeclado;
    private javax.swing.JLabel poste;
    private javax.swing.JTextField tfNombre;
    public javax.swing.JLabel txtBienvenido;
    private javax.swing.JLabel txtDificultad;
    private javax.swing.JLabel txtLapalabraes;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtPalabra;
    private javax.swing.JLabel txtPalabraCorrecta;
    private javax.swing.JLabel txtPerdiste;
    private javax.swing.JLabel txtPista;
    private javax.swing.JLabel vida1;
    private javax.swing.JLabel vida2;
    private javax.swing.JLabel vida3;
    private javax.swing.JButton Ñ;
    // End of variables declaration//GEN-END:variables
}